server:
  port: 0

spring:
  config:
    import: optional:configserver:http://localhost:8079
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: config-server
      username: admin
      password: password
    discovery:
      enabled: true
  name: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka